version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-custom-resource-aurora-serverless-postgres-database"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hqky2ltwhwdk"
s3_prefix = "cfn-custom-resource-aurora-serverless-postgres-database"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
